### ISSUE TITLE
yabridge and various vst plugins error

### ISSUE THREAD

**Issue by bdgraue** [robbert-vdh/yabridge#284]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I tried to use some plugins and can't use them, there is an error, even if yabridge tells me that all should be fine

### What did you expect to happen?

that i can use the plugins in bitwig

### What actually happened?

i get lots of errors when starting bitwig:

Could not find 'libyabridge-vst2.so'
Make sure you followed the installation instructions from yabridge's readme

Source (various/each of the below)

### Operating system

Kubuntu 23.10

### How did you install yabridge?

directly from the release page

### yabridge version

5.0.5

### yabridgectl version

5.0.5

### Wine version

wine-8.21 (Staging)

### Plugin

BBC Symphony Orchestra

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Bitwig 8-Track 5.1 Beta 7

### Desktop environment or WM

KDE Plasma 5.27.9

### GPU model

Mesa Intel® Graphics

### GPU drivers and kernel

Kernel 6.5.0-13-lowlatency (64-bit)

### Debug log

[2023-11-26 17:25:07.436 float-library-metadata info] Starting plugin host process with command: /app/bin/BitwigPluginHost-X64-SSE41 metadata 1234 6 13
PluginHost: Connecting to metadata service with id 6 on port 1234 using id 13
PluginHost: Metadata connection established
PluginHost: Reading VST 3 plugin metadata for /home/mcheng/.vst3/yabridge/SINE Player.vst3
Failed to initialized VST plug-in /home/mcheng/.vst3/yabridge/SINE Player.vst3/Contents/x86_64-linux/SINE Player.so: ModuleEntry() returned false
[2023-11-26 17:25:07.448 float-library-metadata error] Plugin host error Failed to initialized VST plug-in /home/mcheng/.vst3/yabridge/SINE Player.vst3/Contents/x86_64-linux/SINE Player.so: ModuleEntry() returned false
[2023-11-26 17:25:07.448 float-library-metadata info] Closing connection with plugin host: The connection should not be kept alive at the end of the command
Plugin host metadata command reader error: 
[2023-11-26 17:25:07.449 float-document-master error] Error loading file /home/mcheng/.vst3/yabridge/SINE Player.vst3:
        com.bitwig.base.io.RZC: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Failed to initialized VST plug-in /home/mcheng/.vst3/yabridge/SINE Player.vst3/Contents/x86_64-linux/SINE Player.so: ModuleEntry() returned false
        at ZIv.Ves(SourceFile:40)
        at ZIv.ElR(SourceFile:14)
        at Xd.cVe(SourceFile:401)
        at BFE.run(SourceFile:88)
        at d2r.run(SourceFile:307)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Failed to initialized VST plug-in /home/mcheng/.vst3/yabridge/SINE Player.vst3/Contents/x86_64-linux/SINE Player.so: ModuleEntry() returned false
        at com.bitwig.flt.library.metadata.reader.xs3.Ves(SourceFile:174)
        at com.bitwig.flt.library.metadata.reader.xs3.EmI(SourceFile:31)
        at com.bitwig.flt.library.metadata.reader.fbN.bix(SourceFile:14)
        at com.bitwig.flt.library.metadata.reader.gpW.Ves(SourceFile:22)
        at com.bitwig.flt.library.metadata.reader.gpW.EmI(SourceFile:10)
        at com.bitwig.flt.library.metadata.reader.ajl.EmI(SourceFile:41)
        at com.bitwig.flt.library.metadata.reader.ajl.EmI(SourceFile:41)
        at com.bitwig.flt.library.metadata.reader.gIw.Ves(SourceFile:44)
        at com.bitwig.flt.library.metadata.reader.gIw.EmI(SourceFile:20)
        at com.bitwig.flt.library.metadata.reader.zgi.EmI(SourceFile:22)
        at ZIv.Ves(SourceFile:36)
        ... 7 more
Caused by: java.io.IOException: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Failed to initialized VST plug-in /home/mcheng/.vst3/yabridge/SINE Player.vst3/Contents/x86_64-linux/SINE Player.so: ModuleEntry() returned false
        at com.bitwig.flt.library.metadata.reader.Cog.Ves(SourceFile:95)
        at com.bitwig.flt.library.metadata.reader.Cog.Ves(SourceFile:81)
        at Gbs.ElR(SourceFile:187)
        at Gbs.Ves(SourceFile:307)
        at com.bitwig.flt.library.metadata.reader.xs3.Ves(SourceFile:170)
        ... 17 more
Caused by: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Failed to initialized VST plug-in /home/mcheng/.vst3/yabridge/SINE Player.vst3/Contents/x86_64-linux/SINE Player.so: ModuleEntry() returned false
        at com.bitwig.flt.library.metadata.reader.geB.Ves(SourceFile:44)
        at com.bitwig.flt.library.metadata.reader.geB.EmI(SourceFile:10)
        at com.bitwig.flt.library.metadata.reader.Cog.Ves(SourceFile:87)
        ... 21 more
Caused by: com.bitwig.flt.library.metadata.reader.Vwy: Failed to initialized VST plug-in /home/mcheng/.vst3/yabridge/SINE Player.vst3/Contents/x86_64-linux/SINE Player.so: ModuleEntry() returned false
        at com.bitwig.flt.library.metadata.reader.VbL.MAT(SourceFile:1208)
        at com.bitwig.flt.library.metadata.reader.VbL.Ves(SourceFile:454)
        at com.bitwig.flt.library.metadata.reader.VbL.ElR(SourceFile:440)
        at com.bitwig.flt.library.metadata.reader.VbL.Ves(SourceFile:1023)
        at com.bitwig.flt.library.metadata.reader.VbL.Ves(SourceFile:440)
        at com.bitwig.flt.library.metadata.reader.DOA.Ves(SourceFile:143)
        at com.bitwig.flt.library.metadata.reader.DOA.Ves(SourceFile:127)
        at com.bitwig.flt.library.metadata.reader.geB.Ves(SourceFile:32)
        ... 23 more

### Anything else?

$ yabridgectl status
yabridge path: <auto>
VST2 location: '/home/mcheng/.vst/yabridge'
VST3 location: '/home/mcheng/.vst3/yabridge'
CLAP location: '/home/mcheng/.clap/yabridge'

libyabridge-chainloader-vst2.so: '/home/mcheng/.local/share/yabridge/libyabridge-chainloader-vst2.so' (64-bit)
libyabridge-chainloader-vst3.so: '/home/mcheng/.local/share/yabridge/libyabridge-chainloader-vst3.so' (64-bit)
libyabridge-chainloader-clap.so: '/home/mcheng/.local/share/yabridge/libyabridge-chainloader-clap.so' (64-bit)

yabridge-host.exe: '/home/mcheng/.local/share/yabridge/yabridge-host.exe'
yabridge-host-32.exe: '/home/mcheng/.local/share/yabridge/yabridge-host-32.exe'

/home/mcheng/.wine/drive_c/Program Files/Avid/Audio/Plug-Ins/

/home/mcheng/.wine/drive_c/Program Files/Native Instruments/VSTPlugins 64 bit/
  Kontakt.dll :: VST2, 64-bit, synced
  Raum.dll :: VST2, 64-bit, synced
  Reaktor 6 FX.dll :: VST2, 64-bit, synced
  Reaktor 6.dll :: VST2, 64-bit, synced
  Replika.dll :: VST2, 64-bit, synced
  Supercharger.dll :: VST2, 64-bit, synced

/home/mcheng/.wine/drive_c/Program Files/Orchestral Tools/SINE Player/Download/

/home/mcheng/.wine/drive_c/Program Files/Steinberg/VstPlugins/
  Vinyl.dll :: VST2, 64-bit, synced

/home/mcheng/.wine/drive_c/Program Files/VST3/SINE Player.vst3/
   :: VST3, bundle, 64-bit, synced

/home/mcheng/.wine/drive_c/Program Files/VstPlugins/
  BBC Symphony Orchestra (64 Bit).dll :: VST2, 64-bit, synced
  LABS.dll :: VST2, 64-bit, synced
  SINE Player.dll :: VST2, 64-bit, synced

/home/mcheng/.wine/drive_c/Program Files/Vstplugins/
  SINE Player.dll :: VST2, 64-bit, synced

**Comment by bdgraue** [comment]
i have these errors with the flatpak version. with the ubuntu .deb package that error seems to be gone
